### ISSUE TITLE
Issue when editing one of my ressource

### ISSUE THREAD

**Issue by VincentGarreau** [Akryum/moquerie#4]
I have the snapshot bellow:

[snapshots.zip](https://github.com/user-attachments/files/17343586/snapshots.zip)

When I want to edit or create an **EventType** resource I have the error that is displayed in the video
Editing works for the other resources
https://www.loom.com/share/abb8af2131d74d04b568d8cb80c34542

Error:
```
Cannot read properties of undefined (reading 'fields')
TypeError: Cannot read properties of undefined (reading 'fields') at Proxy. (http://localhost:3000/_nuxt/Ca0v2rL3.js:1:6293) at Ga (http://localhost:3000/_nuxt/DlXgYwYr.js:15:31682) at qp.J [as fn] (http://localhost:3000/_nuxt/DlXgYwYr.js:15:23325) at qp.run (http://localhost:3000/_nuxt/DlXgYwYr.js:10:1741) at B (http://localhost:3000/_nuxt/DlXgYwYr.js:15:23716) at M (http://localhost:3000/_nuxt/DlXgYwYr.js:15:22288) at R (http://localhost:3000/_nuxt/DlXgYwYr.js:15:22080) at g (http://localhost:3000/_nuxt/DlXgYwYr.js:15:18903) at C (http://localhost:3000/_nuxt/DlXgYwYr.js:15:20386) at T (http://localhost:3000/_nuxt/DlXgYwYr.js:15:21817)
```

**Comment by TimvdEijnden** [comment]
I've also started to experiment with moquery and run into the same issue, I also got this error in the UI and this one on the terminal:

```
[nuxt] [request error] [unhandled] [500] The locale data for 'system.directoryPaths' are missing in this locale.
  Please contribute the missing data to the project or use a locale/Faker instance that has these data.
  For more information see https://fakerjs.dev/guide/localization.html
  Please contribute the missing data to the project or use a locale/Faker instance that has these data.  
  ```
